### ISSUE TITLE
按照你的步骤，操作失败

### ISSUE THREAD

**Issue by ls9527** [piscium2010/cos-wx-upload-file#1]
把申请到的腾讯的存储桶做了跨域
在微信那边添加了域名
bucket的名称都是按照test-000这样的格式。
最后返回："AccessDenied"

QQ:3641733778   求助

**Comment by ZJYCP** [comment]
我也是，怎么解决？？？

**Comment by YipZong** [comment]
可能是存储桶的存储桶访问权限设置不对？设置为“公有读写”试试。
或者检查congif.js里的SecretId和SecretKey是否正确。

**Comment by ZitionChan** [comment]
这样实现不会有暴露SecretId, SecretKey的风险吗

**Comment by baotlake** [comment]
用户管理里授权对象储存相关权限就可以了

**Comment by lilili001** [comment]
遇到同样的问题, 存储桶为共有读写时可以上传, 私有读写时返回403

**Comment by gerhardtEyes** [comment]
我是pc可以上传 手机预览无法上传 提示请求失败：undefined；状态码：undefined 求助一下
